### ISSUE TITLE
Complex numbers

### ISSUE THREAD

**Issue by Gymmasssorla** [arguiot/TheoremJS#2]
**Complex numbers**
I think that your library needs to get a complex numbers.

**Actions with complex numbers**
You can implement these basic actions with complex numbers:
 - Addition
 - Subtraction
 - Multiplication
 - Division
 - Raise to the power
 - Root
 - Some trigonometrical functions

**Useful references**
 - [Wikipedia](https://en.wikipedia.org/wiki/Complex_number)
 - [StackOverflow](https://stackoverflow.com/questions/15399340/how-to-calculate-with-imaginary-numbers-in-javascript#16530895)
 - [JS library](https://github.com/patrickroberts/complex-js)

**Comment by arguiot** [comment]
It shouldn’t be hard to implement, but I’ll need to do it separately from the current way TheoremJS handles numbers. You can expect that this feature will be available in the next release.

**Comment by arguiot** [comment]
I also have one more question: shall I change the current square root function so negative numbers output complex numbers?

**Comment by Gymmasssorla** [comment]
I do not understand much about your framework, but it is necessary to segregate the root of complex numbers and real numbers unambiguously, since real numbers have one root, complex numbers have an vector of roots.

**Comment by arguiot** [comment]
I'm sorry you don't understand much about TheoremJS.

For the moment, I think TheoremJS will only support very basic support of complex numbers. PRs are open for more advanced operations.

**Comment by arguiot** [comment]
As I almost finished the support of complex numbers on TheoremJS, is there anything you want me to add before the release?

BTW, I probably won't add nth roots for complex numbers, but only sqrt.

**Comment by Gymmasssorla** [comment]
Hello, I think that your library is completely ready for the next release!

**Comment by arguiot** [comment]
@Gymmasssorla one more question: how shall I tag the next release? v1.2.0 or v2.0.0?

For the moment, I'm going to continue to add more features to TheoremJS. I'll release everything in October or sooner if all the bugs are fixed by this time.

**Comment by Gymmasssorla** [comment]
To adhere to the sequence of numbering releases, v1.2.0 will be much better.

**Comment by arguiot** [comment]
Ok, great. I’ll follow your advice.

**Comment by arguiot** [comment]
As v1.2.0 was released, I close this issue. If there is anything else I can do, don't hesitate 😊
