### ISSUE TITLE
UMD/AMD package

### ISSUE THREAD

**Issue by tmcw** [arguiot/TheoremJS#4]
TheoremJS has a browser-friendly `dist` but it'd be excellent if that dist was a UMD or an AMD, so that loaders like `d3-require` could consume it.

Given the rigger-based build system I'm not sure what the right path to this goal would be, because I've never used rigger and it's quite a bit different from something like rollup or browserify, which would make UMD builds rather straightforward.

**Comment by arguiot** [comment]
Hmm, are you sure that TheoremJS doesn't support UMD / AMD? Here is the `export.js` file that is copied at the end of the file:
```
// Browserify / Node.js
if (typeof define === "function" && define.amd) {
  define(() => new TheoremJS());
  // CommonJS and Node.js module support.
} else if (typeof exports !== "undefined") {
  // Support Node.js specific `module.exports` (which can be a function)
  if (typeof module !== "undefined" && module.exports) {
    exports = module.exports = new TheoremJS();
  }
  // But always support CommonJS module 1.1.1 spec (`exports` cannot be a function)
  exports.TheoremJS = new TheoremJS();
} else if (typeof global !== "undefined") {
  global.TheoremJS = new TheoremJS();
}
```

I'm using `gulp-rigger` instead of webpack, ... because it doesn't add extra piece of code, so the build is smaller. It's also much easier for me, because I don't need to write `module.exports` at the end of each file.

**Comment by arguiot** [comment]
@tmcw I'm closing this issue as I'm not sure why you opened it. If you want to reopen it, just add a comment telling so 😊.

**Comment by tmcw** [comment]
Sure, the gist is that the module has `define`, like an AMD package, but it also uses `require`, like a CommonJS module. So there isn't a UMD/AMD implementation that will be able to use it. See, for example, the [amdWeb example](https://github.com/umdjs/umd/blob/master/templates/amdWeb.js) - dependencies are brought in as the first array argument to the `define` function.

**Comment by arguiot** [comment]
Ok, so tell me if I'm wrong but you're asking me to add `.amdWeb` in `export.js`?
